package report

import (
	"fmt"
	"io"

	"github.com/spbuilds/repohealth/internal/model"
)

// HTML renders the report as a standalone HTML document with inline CSS.
func HTML(w io.Writer, r *model.Report) {
	fmt.Fprintln(w, `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RepoHealth Report</title>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #333; }
h1 { border-bottom: 2px solid #eee; padding-bottom: 10px; }
.score { font-size: 48px; font-weight: bold; margin: 20px 0; }
.grade { font-size: 24px; color: #666; }
.score-a { color: #22c55e; }
.score-b { color: #3b82f6; }
.score-c { color: #eab308; }
.score-d { color: #ef4444; }
.score-f { color: #dc2626; }
table { width: 100%; border-collapse: collapse; margin: 20px 0; }
th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #eee; }
th { background: #f8f9fa; font-weight: 600; }
.status-full { color: #22c55e; }
.status-partial { color: #eab308; }
.status-none { color: #ef4444; }
.status-skipped { color: #9ca3af; }
.suggestion { padding: 6px 0; }
.impact { font-weight: bold; color: #3b82f6; }
footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #999; font-size: 14px; }
</style>
</head>
<body>`)

	// Header
	fmt.Fprintf(w, "<h1>Repository Health Report</h1>\n")
	fmt.Fprintf(w, "<p><strong>Repository:</strong> <code>%s</code></p>\n", r.RepoPath)
	if len(r.Timestamp) >= 10 {
		fmt.Fprintf(w, "<p><strong>Date:</strong> %s</p>\n", r.Timestamp[:10])
	}

	// Score
	scoreClass := "score-f"
	if r.Score >= 85 {
		scoreClass = "score-a"
	} else if r.Score >= 70 {
		scoreClass = "score-b"
	} else if r.Score >= 55 {
		scoreClass = "score-c"
	} else if r.Score >= 40 {
		scoreClass = "score-d"
	}
	fmt.Fprintf(w, "<div class=\"score %s\">%d / %d <span class=\"grade\">(%s)</span></div>\n",
		scoreClass, r.Score, r.MaxScore, r.Grade)

	// Category table
	fmt.Fprintln(w, "<h2>Category Breakdown</h2>")
	fmt.Fprintln(w, "<table><tr><th>Category</th><th>Score</th><th>Status</th></tr>")
	for _, cat := range r.Categories {
		status := "Needs Improvement"
		statusClass := "status-none"
		pct := 0
		if cat.MaxScore > 0 {
			pct = cat.Score * 100 / cat.MaxScore
		}
		if pct >= 90 {
			status = "Excellent"
			statusClass = "status-full"
		} else if pct >= 70 {
			status = "Good"
			statusClass = "status-partial"
		} else if pct >= 50 {
			status = "Fair"
			statusClass = "status-partial"
		}
		fmt.Fprintf(w, "<tr><td>%s</td><td>%d/%d</td><td class=\"%s\">%s</td></tr>\n",
			cat.Label, cat.Score, cat.MaxScore, statusClass, status)
	}
	fmt.Fprintln(w, "</table>")

	// Checks detail
	fmt.Fprintln(w, "<h2>Check Details</h2>")
	fmt.Fprintln(w, "<table><tr><th>Check</th><th>Status</th><th>Details</th></tr>")
	for _, check := range r.Checks {
		statusIcon := "&#x2717;" // ✗
		statusClass := "status-none"
		switch check.Status {
		case model.StatusFull:
			statusIcon = "&#x2713;" // ✓
			statusClass = "status-full"
		case model.StatusPartial:
			statusIcon = "&#x25D0;" // ◐
			statusClass = "status-partial"
		case model.StatusSkipped:
			statusIcon = "&#x2014;" // —
			statusClass = "status-skipped"
		}
		fmt.Fprintf(w, "<tr><td>%s</td><td class=\"%s\">%s</td><td>%s</td></tr>\n",
			check.Name, statusClass, statusIcon, check.Details)
	}
	fmt.Fprintln(w, "</table>")

	// Suggestions
	if len(r.Suggestions) > 0 {
		fmt.Fprintln(w, "<h2>Top Recommendations</h2>")
		for i, s := range r.Suggestions {
			if i >= 10 {
				break
			}
			fmt.Fprintf(w, "<div class=\"suggestion\"><span class=\"impact\">+%d pts</span> — %s</div>\n",
				s.Impact, s.Message)
		}
	}

	// Improvement plan
	if len(r.Suggestions) > 0 {
		projected := r.Score
		fmt.Fprintln(w, "<h2>Improvement Plan</h2>")
		fmt.Fprintln(w, "<table><tr><th>Action</th><th>Impact</th><th>Projected Score</th></tr>")
		for i, s := range r.Suggestions {
			if i >= 5 {
				break
			}
			projected += s.Impact
			if projected > 100 {
				projected = 100
			}
			fmt.Fprintf(w, "<tr><td>%s</td><td>+%d pts</td><td>%d</td></tr>\n",
				s.Message, s.Impact, projected)
		}
		fmt.Fprintln(w, "</table>")
	}

	// Footer
	fmt.Fprintln(w, `<footer>Generated by <a href="https://github.com/spbuilds/repohealth">RepoHealth</a></footer>`)
	fmt.Fprintln(w, "</body></html>")
}
