package report

import (
	"fmt"
	"io"

	"github.com/spbuilds/repohealth/internal/model"
)

// Markdown renders the report as a Markdown document.
func Markdown(w io.Writer, r *model.Report) {
	fmt.Fprintf(w, "# Repository Health Report\n\n")
	fmt.Fprintf(w, "**Repository:** `%s`\n", r.RepoPath)
	if len(r.Timestamp) >= 10 {
		fmt.Fprintf(w, "**Date:** %s\n", r.Timestamp[:10])
	}
	fmt.Fprintf(w, "**Score:** **%d / %d** (%s)\n\n", r.Score, r.MaxScore, r.Grade)

	fmt.Fprintln(w, "## Category Breakdown")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "| Category | Score | Status |")
	fmt.Fprintln(w, "|----------|-------|--------|")
	for _, cat := range r.Categories {
		status := "Needs Improvement"
		pct := 0
		if cat.MaxScore > 0 {
			pct = cat.Score * 100 / cat.MaxScore
		}
		if pct >= 90 {
			status = "Excellent"
		} else if pct >= 70 {
			status = "Good"
		} else if pct >= 50 {
			status = "Fair"
		}
		fmt.Fprintf(w, "| %s | %d/%d | %s |\n", cat.Label, cat.Score, cat.MaxScore, status)
	}

	if len(r.Suggestions) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "## Top Recommendations")
		fmt.Fprintln(w)
		for i, s := range r.Suggestions {
			if i >= 10 {
				break
			}
			fmt.Fprintf(w, "%d. **+%d pts** — %s\n", i+1, s.Impact, s.Message)
		}
	}

	if len(r.Suggestions) > 0 {
		fmt.Fprintln(w)
		fmt.Fprintln(w, "## Improvement Plan")
		fmt.Fprintln(w)
		fmt.Fprintln(w, "| Action | Impact | Projected Score |")
		fmt.Fprintln(w, "|--------|--------|----------------|")
		projected := r.Score
		for i, s := range r.Suggestions {
			if i >= 5 {
				break
			}
			projected += s.Impact
			if projected > 100 {
				projected = 100
			}
			fmt.Fprintf(w, "| %s | +%d pts | %d |\n", s.Message, s.Impact, projected)
		}
	}

	fmt.Fprintln(w)
	fmt.Fprintln(w, "---")
	fmt.Fprintln(w, "*Generated by [RepoHealth](https://github.com/spbuilds/repohealth)*")
}
